### ISSUE TITLE
_pickle.UnpicklingError: Could not load model from artifact file: invalid load key, 'v'.

### ISSUE THREAD

**Issue by albertotonon** [datarobot/datarobot-user-models#194]
Hello and thanks for the nice tutorial. I've just run the quick start and got the error stack trace you can find at the end of this message.

I'm running in a Python3.8 virtual environment with the libraries listed in the venv.txt. Here are the history of the commands i've run:
```bash
python3.8 -m venv venv/
source venv/bin/activate
cd datarobot-user-models
pip install -r public_dropin_environments/python3_sklearn/requirements.txt
drum
which python
pip install datarobot-drum
drum score --code-dir model_templates/inference/python3_sklearn --input tests/testdata/boston_housing.csvtests/testdata/boston_housing.csv
```

[venv.txt](https://github.com/datarobot/datarobot-user-models/files/5457092/venv.txt)

❯ drum score --code-dir model_templates/inference/python3_sklearn --input tests/testdata/boston_housing.csv
Traceback (most recent call last):
  File "/Users/albton/Projects/Pricing/AS24-PriceEstimation-Experiments/Experiments/TestMLOps/venv/bin/drum", line 6, in <module>
    main()
  File "/Users/albton/Projects/Pricing/AS24-PriceEstimation-Experiments/Experiments/TestMLOps/venv/lib/python3.8/site-packages/datarobot_drum/drum/main.py", line 96, in main
    CMRunner(runtime).run()
  File "/Users/albton/Projects/Pricing/AS24-PriceEstimation-Experiments/Experiments/TestMLOps/venv/lib/python3.8/site-packages/datarobot_drum/drum/drum.py", line 286, in run
    self._run_fit_and_predictions_pipelines_in_mlpiper()
  File "/Users/albton/Projects/Pricing/AS24-PriceEstimation-Experiments/Experiments/TestMLOps/venv/lib/python3.8/site-packages/datarobot_drum/drum/drum.py", line 551, in _run_fit_and_predictions_pipelines_in_mlpiper
    _pipeline_executor.init_pipeline()
  File "/Users/albton/Projects/Pricing/AS24-PriceEstimation-Experiments/Experiments/TestMLOps/venv/lib/python3.8/site-packages/mlpiper/pipeline/executor.py", line 257, in init_pipeline
    self._init_pipeline()
  File "/Users/albton/Projects/Pricing/AS24-PriceEstimation-Experiments/Experiments/TestMLOps/venv/lib/python3.8/site-packages/mlpiper/pipeline/executor.py", line 229, in _init_pipeline
    self._dag.configure_connected_pipeline(
  File "/Users/albton/Projects/Pricing/AS24-PriceEstimation-Experiments/Experiments/TestMLOps/venv/lib/python3.8/site-packages/mlpiper/pipeline/dag.py", line 119, in configure_connected_pipeline
    dag_node.component_runner.configure(input_args)
  File "/Users/albton/Projects/Pricing/AS24-PriceEstimation-Experiments/Experiments/TestMLOps/venv/lib/python3.8/site-packages/mlpiper/pipeline/component_runner/python_connected_component_runner.py", line 10, in configure
    self._dag_node.main_cls().configure(params)
  File "/Users/albton/Projects/Pricing/AS24-PriceEstimation-Experiments/Experiments/TestMLOps/venv/lib/python3.8/site-packages/datarobot_drum/resource/components/Python/generic_predictor/generic_predictor.py", line 57, in configure
    self._predictor.configure(params)
  File "/Users/albton/Projects/Pricing/AS24-PriceEstimation-Experiments/Experiments/TestMLOps/venv/lib/python3.8/site-packages/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py", line 34, in configure
    self._model = self._model_adapter.load_model_from_artifact()
  File "/Users/albton/Projects/Pricing/AS24-PriceEstimation-Experiments/Experiments/TestMLOps/venv/lib/python3.8/site-packages/datarobot_drum/drum/model_adapter.py", line 110, in load_model_from_artifact
    self._model = self._load_via_predictors(model_artifact_file)
  File "/Users/albton/Projects/Pricing/AS24-PriceEstimation-Experiments/Experiments/TestMLOps/venv/lib/python3.8/site-packages/datarobot_drum/drum/model_adapter.py", line 187, in _load_via_predictors
    raise type(exc)(
  File "/Users/albton/Projects/Pricing/AS24-PriceEstimation-Experiments/Experiments/TestMLOps/venv/lib/python3.8/site-packages/datarobot_drum/drum/model_adapter.py", line 185, in _load_via_predictors
    model = pred.load_model_from_artifact(model_artifact_file)
  File "/Users/albton/Projects/Pricing/AS24-PriceEstimation-Experiments/Experiments/TestMLOps/venv/lib/python3.8/site-packages/datarobot_drum/drum/artifact_predictors/sklearn_predictor.py", line 39, in load_model_from_artifact
    model = pickle.load(picklefile, encoding="latin1")
_pickle.UnpicklingError: Could not load model from artifact file: invalid load key, 'v'.
```

**Comment by sroecker** [comment]
Hi Alberto,
did you enable Git LFS like described in our README.md?
If you pull datarobot-user-models without LFS bigger files don't download correctly and these files will contain the text 'version' so pickle fails on the first letter 'v'.

**Comment by albertotonon** [comment]
good catch @sroecker! I don't know why I was thinking that downloading the repo as zip file would include everything. This time as well the bug was between the keyboard and the chair 😅
